#!/usr/bin/env sh

commit_message="$1"
# exit with a non zero exit code in case of an invalid commit message

# use git-conventional-commits, see https://github.com/qoomon/git-conventional-commits
git-conventional-commits commit-msg-hook "$commit_message"

# TODO Overwrite or copy this file to your local repository directory/.git/hooks
